name: Build

on:
  push:
    branches:
      - main

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # - name: Install Python dev package (Ubuntu only)
      #   if: runner.os == 'Linux'
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y python3-dev
      
      # - name: Add conda to system path
      #   run: |
      #     echo $CONDA/bin >> $GITHUB_PATH

      # - name: Install dependencies
      #   run: |
      #     conda env update --file environment.yml --name base
      #     echo "CONDA_BASE_PREFIX=$(conda info --base)" >> $GITHUB_ENV
      - name: Make linux script executable
        if: runner.os == 'Linux'
        run: chmod +x ./dependencies_linux.sh

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-build
          pip install cibuildwheel

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ENVIRONMENT: "CC=/opt/rh/devtoolset-10/root/usr/bin/gcc CXX=/opt/rh/devtoolset-10/root/usr/bin/g++"

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

