name: Build

on:
  push:
    branches:
      - main

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Make linux script executable
        if: runner.os == 'Linux'
        run: chmod +x ./dependencies_linux.sh

      - name: Make mac script executable
        if: runner.os == 'macOS'
        run: chmod +x ./dependencies_mac.sh

      - name: Run Windows dependencies script
        if: runner.os == 'Windows'
        shell: powershell
        run: .\dependencies_windows.ps1

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-build
          pip install cibuildwheel

      - name: Install pybind for windows
        if: runner.os == 'Windows'
        run: pip install pybind11

      - name: Set Python path for windows
        if: runner.os == 'Windows'
        run: echo "PYTHON_PATH=$(where python)" >> $GITHUB_ENV
        shell: pwsh
      
      - name: Set CC and CXX environment variables
        run: |
          echo "CC=$(which gcc)" >> $GITHUB_ENV
          echo "CXX=$(which g++)" >> $GITHUB_ENV
        shell: bash
      
      
      - name: Print PYTHON_PATH
        if: runner.os == 'Windows'
        run: echo $PYTHON_PATH
        shell: pwsh

      - name: Set mac environment variables 
        if: runner.os == 'macOS'
        run: |
          echo "CC=$(which clang)" >> $GITHUB_ENV
          echo "CXX=$(which clang++)" >> $GITHUB_ENV
          echo "OpenMP_LIBRARY=/usr/local/lib/libomp.dylib" >> $GITHUB_ENV

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

